version: '3.4'
services:
  netdata:
    image: netdata/netdata:v1.44.1
    container_name: netdata
    ports:
      - 19999:19999
    volumes:
      - ./data/netdataconfig:/etc/netdata
      - ./data/netdatalib:/var/lib/netdata
      - ./data/netdatacache:/var/cache/netdata
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor=unconfined
    networks:
      - mynet
networks:
      mynet:
        external: true



