version: '3.4'
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    ports:
      - 19999:19999
    volumes:
      - ./data/netdataconfig:/etc/netdata
      - ./data/netdatalib:/var/lib/netdata
      - ./data/netdatacache:/var/cache/netdata
      - ./data/etc/passwd:/host/etc/passwd:ro
      - ./data/etc/group:/host/etc/group:ro
      - ./data/proc:/host/proc:ro
      - ./data/sys:/host/sys:ro
      - ./data/etc/os-release:/host/etc/os-release:ro
#      - ./netdata-captch/index.html:/usr/share/netdata/web/index.html
#      - ./netdata-captch/dashboard.js:/usr/share/netdata/web/dashboard.js
#      - ./netdata-captch/dashboard_info.js:/usr/share/netdata/web/dashboard_info.js
#      - ./netdata-captch/main.js:/usr/share/netdata/web/main.js
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor=unconfined
    networks:
      - mynet
networks:
  mynet:
    external: true



