version: '3.4'
services:

  mysql-master:
#    image: mysql:8.0.14
    image: mysql/mysql-server:8.0.14 #mac
    container_name: mysql-master
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    restart: always
    networks:
      - mynet
  mysql-slave-1:
#    image: mysql:8.0.14
    image: mysql/mysql-server:8.0.14 #mac
    container_name: mysql-slave-1
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3308:3306"
    volumes:
      - ./data/mysql-slave:/var/lib/mysql
      - ./mysql/my-slave.cnf:/etc/mysql/my.cnf
    restart: always
    networks:
      - mynet
networks:
      mynet:
        external: true
