version: '3.3'
services:
  service-database:
    container_name: addx_wallet_container_dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    restart: always
    env_file: .env
    ports:
      - "50052:50052"
    logging:
      options:
        max-size: 10m
    volumes:
      - ./:/app
    networks:
      - mynet
networks:
  mynet:
    external: true
