version: '3.4'
services:
  mysql:
    image: mysql:5.7
#    image: mysql/mysql-server:5.7 #mac
    container_name: ycp-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Shanghai
    ports:
      - "13306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    networks:
      - mynet
  redis:
    container_name: ycp-redis
    image: redis:4-alpine
    ports:
      - "16379:6379"
    sysctls:
      net.core.somaxconn: 65535
    restart: always
    networks:
      - mynet
  mysql-8:
    image: mysql:8.0.14
    #    image: mysql/mysql-server:8.0.14 #mac
    container_name: mysql-8
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    networks:
      - mynet
networks:
      mynet:
        external: true
