version: '3.4'
services:
  mysql-8:
    #    image: mysql:8.0.14
    image: mysql/mysql-server:8.0.14 #mac
    container_name: dev-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "13306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
  redis:
    container_name: dev-redis
    image: redis:6.2.6
    ports:
      - "16379:6379"
    sysctls:
      net.core.somaxconn: 65535
    volumes:
      - ./conf/redis.conf:/etc/redis/redis.conf
      - ./data/redis/data:/data
    command: [ "redis-server","/etc/redis/redis.conf" ]
    restart: always
    networks:
      - my_net
networks:
  my_net:
    external: true
