version: '3.4'
services:
  mysql:
#    image: mysql:5.7
    image: mysql/mysql-server:5.7 #mac
    container_name: dev-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    networks:
      - mynet
  redis:
    container_name: dev-redis
    image: redis:4-alpine
    ports:
      - "6379:6379"
    sysctls:
      net.core.somaxconn: 65535
    restart: always
    networks:
      - mynet
networks:
      mynet:
        external: true
