version: '3.4'
services:
  mysql:
#    image: mysql:5.7
    image: mysql/mysql-server:5.7 #mac
    container_name: dev-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    networks:
      - mynet
  redis:
    container_name: dev-redis
    image: redis:6.2.6
    ports:
      - "6379:6379"
    sysctls:
      net.core.somaxconn: 65535
    volumes:
      - ./conf/redis.conf:/etc/redis/redis.conf
      - ./data/redis/data:/data
    command: [ "redis-server","/etc/redis/redis.conf" ]
    restart: always
    networks:
      - mynet
  nginx:
    image: nginx     # 镜像名称
    container_name: nginx     # 容器名字
    restart: always     # 开机自动重启
    ports: # 端口号绑定（宿主机:容器内）
      - '80:80'
      - '443:443'
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/vhost.conf:/etc/nginx/conf.d/vhost.conf
      - ./conf/vhost_.conf:/etc/nginx/conf.d/vhost.conf
      - ./data/nginx/log:/var/log/nginx
    networks:
      - mynet
networks:
      mynet:
        external: true
