services:
  postgres_db: # 服务名称
    image: postgres:13 # 指定镜像及其版本
    container_name: docker_postgres # 指定容器的名称
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      #POSTGRES_DB: default
    ports: # 端口映射
      - "5432:5432"
    volumes: # 数据持久化的配置
      - ./data:/var/lib/postgresql/data
      - ./log:/var/log/postgresql
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my_net

networks:
  my_net:
    external: true

