version: "3"
services:
  nginx_master:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./keepalived-master.conf:/etc/keepalived/keepalived.conf
      - ./check-nginx.sh:/etc/keepalived/check-nginx.sh
    network_mode: host