version: '3.4'
services:
  shop:
    image: webdevops/php-nginx:8.0
    container_name: php-shop
    environment:
      - APP_ENV=dev
      - PHP_DATE_TIMEZONE=Asia/Shanghai
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/app/
      - ./ci-nginx.conf:/opt/docker/etc/nginx/vhost.conf
    stdin_open: true
    tty: true
#    command: /bin/bashd
    networks:
      - mynet
networks:
  mynet:
    external: true


