version: '3.8'

services:
  consul:
    image: hashicorp/consul:1.20.0
    container_name: consul
    restart: always
    ports:
      - "8500:8500"      # Consul UI 和 HTTP API
      - "8600:8600/udp"  # DNS 服务
    volumes:
      - ./data:/consul/data
      - ./config:/consul/config
    command: agent -server -ui -client=0.0.0.0 -bind=0.0.0.0 -bootstrap-expect=1 -data-dir=/consul/data -config-dir=/consul/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 30s
      retries: 3
      start_period: 5s
    networks:
      - my_net
networks:
  my_net:
    external: true
