version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.7.0  #镜像
    container_name: elk_elasticsearch  #定义容器名称
    restart: always  #开机启动，失败也会一直重启
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m" #设置使用jvm内存大小
    volumes:
      - ./plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - ./data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - "9200:9200"
    networks:
      - mynet
  kibana:
    image: kibana:7.7.0
    container_name: elk_kibana
    restart: always
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    privileged: true    #环境变量
    networks:
      - mynet
  #这里要注意，es和eshd要在相同网络才能被links   hd:连接地址 http://192.168.1.3:19200  http://ip地址:19200  或者配置跨域http.cors.enabled: true http.cors.allow-origin: "*"
networks:
  mynet:
    external: true