version: '3.4'
services:
  nginx_prod:
    image: nginx:1.25.3-alpine
    container_name: nginx_prod
    restart: always
    volumes:
      - ./deploy/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./deploy/nginx/conf/vhost_prod.conf:/etc/nginx/conf.d/default.conf
      - ./deploy/nginx/data/nginx/log:/var/log/nginx
#      - ./deploy/nginx/conf/cert/ssl/tools.aimaster.space.key:/etc/nginx/cert/tools.aimaster.space.key
#      - ./deploy/nginx/conf/cert/ssl/tools.aimaster.space.pem:/etc/nginx/cert/tools.aimaster.space.pem
    network_mode: host
#networks:
#  my_net:
#    external: true


