version: '3.4'
services:
  redis:
    container_name: redis
    image: redis:6.2.6
    ports:
      - "16379:6379"
    sysctls:
      net.core.somaxconn: 65535
    volumes:
      - ./conf/redis.conf:/etc/redis/redis.conf
      - ./data/redis/data:/data
    command: [ "redis-server","/etc/redis/redis.conf" ]
    restart: always
    networks:
      - prod-network
  mysql-8:
    image: mysql:8.0.14
    #    image: mysql/mysql-server:8.0.14 #mac
    container_name: mysql-8
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "13306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/mysql-files:/var/lib/mysql-files # 导入/导出文件限制目录
      - ./conf/my.cnf:/etc/mysql/my.cnf
    restart: always
    networks:
      - prod-network
  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx
    restart: always
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/conf:/etc/nginx/conf.d
      - ./data/nginx/log:/var/log/nginx
      - /root/.acme.sh/:/root/.acme.sh/
      - /root/dist:/root/dist/
    network_mode: host
  minio:
    image: minio/minio:latest
    hostname: "minio"
    ports:
      - 9000:9000 # api 端口
      - 9001:9001 # 控制台端口
    environment:
      MINIO_ACCESS_KEY: admin    #管理后台用户名
      MINIO_SECRET_KEY: admin_yide #管理后台密码，最小8个字符
    volumes:
      - ./minio/data:/data               #映射当前目录下的data目录至容器内/data目录
      - ./minio/config:/root/.minio/     #映射配置目录
    command: server --console-address ':9001' /data  #指定容器中的目录 /data
    privileged: true
    restart: always
    networks:
      - prod-network
networks:
  prod-network:
    external: true


