version: '3.4'
services:
  swoft:
    image: webdevops/php-nginx:7.3
    container_name: web
    environment:
      - APP_ENV=dev
      - PHP_DATE_TIMEZONE=Asia/Shanghai
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/app/
      - ./ci-nginx.conf:/opt/docker/etc/nginx/vhost.conf
    networks:
      - my_net
networks:
  my_net:
    external: true


